### ISSUE TITLE
Deriva AUTH - UI buttons non-responsive after restoring from minified form

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/deriva-qt#2]
Env: Mac OS 10.13.1

example:
1. launch Deriva AUTH
2. login to a host
3. minimize the app
4. bring the app back to the desktop/foreground
5. buttons now do not respond for the most part (e.g., logout doesn't respond)

**Comment by mikedarcy** [comment]
Fixed in 846a7b7.  Will get rolled into next release.
Test bundle for OSX [here](http://buildbot.isrd.isi.edu/~buildbot/deriva-qt/macos/DERIVA-Auth-0.4.1-osx.zip).

**Comment by mikedarcy** [comment]
@robes Would you mind testing the latest MacOS bundle on buildbot and verify that this issue is fixed?
