### ISSUE TITLE
ambiguous hostname specification

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/deriva-qt#4]
I am not sure whether the script expect `https` or can handle `https://` as a prefix. Can we make the help message clearer or make the script handle the prefix?

**Comment by mikedarcy** [comment]
I've committed a fix for this in: de46831.  Both the uploader and the auth-agent should be able to deal with the protocol specifier in the hostname now.  Basically, it gets stripped out if it is specified, and https is always used internally.
