### ISSUE TITLE
run deriva-auth gave a core dump after adding server name

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/deriva-qt#6]
I tried both dev.rebuildingakidney.org and dev.facebase.org. The first doesn't have the bulk-upload annotation.. 

I am not sure whether it is relevant to #3 or not..

**Comment by mikedarcy** [comment]
Based on our slack discussion, it looks like this is an installation issue when building from source on Fedora.  After a server name is added, the app attempts to create the corresponding login session via QtWebEngine, and if there is a problem with the installation of that dependency, then core dumps are possible.  I am not sure what we can do to guard against such a scenario from within the code itself...

Can we close this issue?
